#!/bin/bash
toolchain_path=/opt/fsl-imx-xwayland/4.14-sumo/sysroots
toolchain="${toolchain_path}/x86_64-pokysdk-linux"
rootfs="${toolchain_path}/my_aarch64-poky-linux"
rm build_imx8 -rf
mkdir build_imx8
cd build_imx8
cmake .. \
-DQT5_PATH="${rootfs}/usr" \
-DCMAKE_C_COMPILER="${toolchain}/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc" \
-DCMAKE_CXX_COMPILER="${toolchain}/usr/bin/aarch64-poky-linux/aarch64-poky-linux-g++" \
-DCMAKE_C_COMPILER_ARG1="--sysroot=${rootfs}" \
-DCMAKE_CXX_COMPILER_ARG1="--sysroot=${rootfs}" \
-DOE_QMAKE_PATH_EXTERNAL_HOST_BINS="${toolchain}/usr/bin/qt5"
make -j4
